dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

services:
  - postgresql


before_install:
  - export DJANGO_SETTINGS_MODULE=core.settings.test

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - cp .env.test .env
  - cp .admins.example .admins

install:
  - pip install -r requirements/test.txt

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py check
  - coverage run --source='.' manage.py test area
  - coverage report
  - coverage xml
  - python-codacy-coverage -r coverage.xml

after_success:
  - coveralls