#  Copyright (c) 2019 - 2019. Abhimanyu Saharan <desk.abhimanyu@gmail.com> and the Play.It contributors

"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

from decouple import config

# Site ID
SITE_ID = 1

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = os.path.abspath(os.path.join(BASE_DIR, ".."))

# Admins
try:
	with open(os.path.abspath(os.path.join(PROJECT_DIR, '.admins')), 'r')as f:
		admins = [tuple(map(str, i.split(','))) for i in f]
	ADMINS = admins
except FileNotFoundError:
	raise Exception(".admins file is missing. Exiting...")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', cast=str)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

# Application definition
DJANGO_APPS = [
		'django.contrib.admin',
		'django.contrib.auth',
		'django.contrib.contenttypes',
		'django.contrib.sessions',
		'django.contrib.messages',
		'django.contrib.staticfiles',
]

LOCAL_APPS = [
		'area',
		'artist'
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS

DJANGO_SECURITY_MIDDLEWARE = [
		'django.middleware.security.SecurityMiddleware',
]

DJANGO_CACHE_MIDDLEWARE = [
		'django.middleware.cache.UpdateCacheMiddleware',
		'django.middleware.cache.FetchFromCacheMiddleware'
]

DJANGO_MIDDLEWARE = [
		'django.contrib.sessions.middleware.SessionMiddleware',
		'django.middleware.common.CommonMiddleware',
		'django.middleware.csrf.CsrfViewMiddleware',
		'django.contrib.auth.middleware.AuthenticationMiddleware',
		'django.contrib.messages.middleware.MessageMiddleware',
		'django.middleware.clickjacking.XFrameOptionsMiddleware',
		'django.middleware.common.CommonMiddleware',
		'django.middleware.http.ConditionalGetMiddleware',
]

MIDDLEWARE = DJANGO_SECURITY_MIDDLEWARE + DJANGO_CACHE_MIDDLEWARE + DJANGO_MIDDLEWARE

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
		{
				'BACKEND':  'django.template.backends.django.DjangoTemplates',
				'DIRS':     [os.path.join(PROJECT_DIR, 'templates')],
				'APP_DIRS': True,
				'OPTIONS':  {
						'context_processors': [
								'django.template.context_processors.debug',
								'django.template.context_processors.request',
								'django.contrib.auth.context_processors.auth',
								'django.contrib.messages.context_processors.messages',
						],
				},
		},
]

WSGI_APPLICATION = 'core.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
		{
				'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
		},
		{
				'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
		},
		{
				'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
		},
		{
				'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
		},
]

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
		'default': {
				'ENGINE':   config('DB_ENGINE', cast=str),
				'NAME':     config('DB_NAME', cast=str),
				'USER':     config('DB_USER', cast=str),
				'PASSWORD': config('DB_PASSWORD', cast=str, default=''),
				'HOST':     config('DB_HOST', cast=str),
				'PORT':     config('DB_PORT', cast=str)
		}
}

# Email Settings
EMAIL_HOST = config('EMAIL_HOST', cast=str)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', cast=str)
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', cast=str)
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = config('LANGUAGE_CODE', cast=str)

TIME_ZONE = config('TIME_ZONE', cast=str)

USE_I18N = config('USE_I18N', cast=bool)

USE_L10N = config('USE_L10N', cast=bool)

USE_TZ = config('USE_TZ', cast=bool)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATICFILES_DIRS = (os.path.join(PROJECT_DIR, 'static'),)
STATIC_ROOT = os.path.abspath(os.path.join(PROJECT_DIR, 'staticfiles/'))
MEDIA_ROOT = os.path.abspath(os.path.join(PROJECT_DIR, 'media/'))

MEDIA_LOGS = os.path.abspath(os.path.join(MEDIA_ROOT, 'logs'))

if not os.path.exists(MEDIA_LOGS):
	os.makedirs(MEDIA_LOGS)

if not os.path.exists(STATIC_ROOT):
	os.makedirs(STATIC_ROOT)

for static_dirs in STATICFILES_DIRS:
	if not os.path.exists(static_dirs):
		os.makedirs(static_dirs)

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
